config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/admin" => "homes#top"
  get "homes/about"=> "homes#about",as:"about"
  
  get "admin/searches/search" => "admin/searches#search",as:"admin_search"
  get "admin/searches/genre_search" => "admin/searches#genre_search",as:"admin_genre_search"
  
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,except: [:destroy]
    resources :customers,only: [:index,:edit,:update,:show]
    resources :orders,only:[:show,:update,:index]
    resources :order_details,only:[:update]
  end
  
  devise_for :admin,skip: [:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }
  
  get "customers/my_page" => "public/customers#show",as:"my_page"
  get "customers/unsubscribe" => "public/customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdraw" => "public/customers#withdraw",as:"withdraw"
  delete "cart_items/destroy_all" => "public/cart_items#destroy_all",as:"destroy_all"
  get "orders/complete" => "public/orders#complete",as:"complete"
  post "orders/confirm" => "public/orders#confirm",as:"confirm"
  get "searches/search" => "public/searches#search",as:"search"
  get "searches/genre_search" => "public/searches#genre_search",as:"genre_search"
  
  scope module: :public do
    resource :customers,except: [:new,:create]
    resources :addresses,except: [:show,:new]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:create,:update,:destroy]
    resources :orders,only:[:index,:new,:create,:show]
  end
  
  devise_for :customers,skip: [:passwords,],controllers:{
     registrations: "public/registrations",
     sessions: "public/sessions"
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  belongs_to :customer
  
  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true
  belongs_to :customer
  belongs_to :item
  validates :amount,presence: true
  
  def subtotal
    item.with_tax_price*amount
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name,presence: true
  has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  attachment :image
  validates :image,presence: true
  
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card:0,transfer:1}
  enum order_status: {waiting:0,confirmation:1,making:2,preparation:3,sent:4}
  belongs_to :customer
  has_many :order_details,dependent: :destroy
  
  def address_display
    "〒" + shipping_postal + " " + shipping_address + " " + shipping_name
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: {not_startable:0,waiting:1,making:2,complete:3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:first_name,:first_name_kana,:last_name,:last_name_kana,:email,:postal_code,:address,:telephone_number,:is_delete)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    genres = Genre.all
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path(genres)
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    genres = Genre.all
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genres)
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @genres = Genre.all
    @item = Item.new
  end
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    @orders = Order.page(params[:page]).order(id: "desc").per(8)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.order_status == "confirmation"
      order.order_details.update_all(making_status: "waiting")
    end
    order.save
    redirect_to admin_order_path(order.id)
  end
  
  private
  
  def order_params
    params.require(:order).permit(:order_status)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def test
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @genres = Genre.all
  end
  
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  
  <div class="row mb-2">
    <h4 class="offset-1 bg-light"><%= "#{@customer.last_name + @customer.first_name}さん" %>の会員編集</h1>
  </div>
    <%= form_with model: @customer,url: admin_customer_path,local:true do |f| %>
      
      
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">会員ID</h6>
        <div class="col-3">
          <%= @customer.id %>
        </div>
      </div>
      
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">名前</h6>
        <div class="col-3">
          <%= f.text_field :last_name,autofocus: true ,class:"form-control"%>
        </div>
        <div class="col-3">
          <%= f.text_field :first_name,autofocus: true,class:"form-control" %>
        </div>
      </div>
      
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">フリガナ</h6>
        <div class="col-3">
          <%= f.text_field :last_name_kana,autofocus: true ,class:"form-control"%>
        </div>
        <div class="col-3">
          <%= f.text_field :first_name_kana,autofocus: true,class:"form-control" %>
        </div>
      </div>
      
    
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">メールアドレス</h6>
        <div class="col-3">
          <%= f.email_field :email, autofocus: true, autocomplete: "email",class:"form-control",placeholder:"sample@example.com" %>
        </div>
      </div>
    
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">郵便番号（ハイフンなし）</h6>
        <div class="col-3">
          <%= f.text_field :postal_code, autofocus: true,class:"form-control",placeholder:"0000000" %>
        </div>
      </div>
      
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">住所</h6>
        <div class="col-7">
          <%= f.text_field :address, autofocus: true,class:"form-control",placeholder:"東京都渋谷区" %>
        </div>
      </div>
      
      <div class="row g-3 align-items-center mb-3">
        <h6 class="col-3">電話番号（ハイフンなし）</h6>
        <div class="col-3">
          <%= f.text_field :telephone_number, autofocus: true,class:"form-control",placeholder:"00000000000" %>
        </div>
      </div>
      
      <div class="row mb-3 align-items-center mb-3">
        <label class="col-3">会員ステータス</label>
        <div class="col-3">
          <div class="form-check-inline">
            <div class="form-check pl-0">
              <label class="form-check-label"><%= f.radio_button :is_delete,true %>販売中</label>
            </div>
            <div class="form-check">
               <label class="form-check-label"><%= f.radio_button :is_delete,false %>販売停止中</label>
            </div>
          </div>
        </div>
      </div>
      
    
      <div class="row g-3 align-items-center mb-3">
        <%= f.submit "変更を保存",class:"btn btn-success offset-3 col-2"%>
      </div>
<% end %>
  

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mb-2">
    <h4 class="offset-1 bg-light">会員一覧</h1>
  </div>
  
  <div class="row">
    <table class="table w-75 mx-auto">
      <thead>
        <tr>
          <th class="table-active" width="100">会員ID</th>
          <th class="table-active" width="200">名前</th>
          <th class="table-active" width="250">メールアドレス</th>
          <th class="table-active" width="100">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name,admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td><%= customer.is_delete ? "有効" : "退会" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mb-2">
    <h4 class="offset-1 bg-light"><%= "#{@customer.last_name + @customer.first_name}さん" %>の会員詳細</h1>
  </div>
  
  <div class="row">
    <table class="table table-borderless">
      <tbody>
          <tr>
            <td style="width:15%;">会員ID</td>
            <td ><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name + @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%=  @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%= @customer.is_delete ?  "有効" : "退会" %></td>
          </tr>
          <tr>
            <td></td>
            <td>
              <%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-success mr-5" %>
              <%= link_to "注文履歴一覧を見る",admin_orders_path(@customer.id),class:"btn btn-primary" %>
            </td>
          </tr>
      </tbody>
    </table>
  </div>
</div>