config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/admin" => "homes#top"
  get "homes/about"=> "homes#about",as:"about"
  
  get "admin/searches/search" => "admin/searches#search",as:"admin_search"
  get "admin/searches/genre_search" => "admin/searches#genre_search",as:"admin_genre_search"
  
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,except: [:destroy]
    resources :customers,only: [:index,:edit,:update,:show]
    resources :orders,only:[:show,:update,:index]
    resources :order_details,only:[:update]
  end
  
  devise_for :admin,skip: [:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }
  
  get "customers/my_page" => "public/customers#show",as:"my_page"
  get "customers/unsubscribe" => "public/customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdraw" => "public/customers#withdraw",as:"withdraw"
  delete "cart_items/destroy_all" => "public/cart_items#destroy_all",as:"destroy_all"
  get "orders/complete" => "public/orders#complete",as:"complete"
  post "orders/confirm" => "public/orders#confirm",as:"confirm"
  get "searches/search" => "public/searches#search",as:"search"
  get "searches/genre_search" => "public/searches#genre_search",as:"genre_search"
  
  scope module: :public do
    resource :customers,except: [:new,:create]
    resources :addresses,except: [:show,:new]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:create,:update,:destroy]
    resources :orders,only:[:index,:new,:create,:show]
  end
  
  devise_for :customers,skip: [:passwords,],controllers:{
     registrations: "public/registrations",
     sessions: "public/sessions"
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  belongs_to :customer
  
  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true
  belongs_to :customer
  belongs_to :item
  validates :amount,presence: true
  
  def subtotal
    item.with_tax_price*amount
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name,presence: true
  has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  attachment :image
  validates :image,presence: true
  
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card:0,transfer:1}
  enum order_status: {waiting:0,confirmation:1,making:2,preparation:3,sent:4}
  belongs_to :customer
  has_many :order_details,dependent: :destroy
  
  def address_display
    "〒" + shipping_postal + " " + shipping_address + " " + shipping_name
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: {not_startable:0,waiting:1,making:2,complete:3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    genres = Genre.all
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path(genres)
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    genres = Genre.all
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genres)
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @genres = Genre.all
    @item = Item.new
  end
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    @orders = Order.page(params[:page]).order(id: "desc").per(8)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.order_status == "confirmation"
      order.order_details.update_all(making_status: "waiting")
    end
    order.save
    redirect_to admin_order_path(order.id)
  end
  
  private
  
  def order_params
    params.require(:order).permit(:order_status)
  end
  
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def test
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @genres = Genre.all
  end
  
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  
  <div class="row mb-2">
    <h4 class="offset-1 bg-light">ジャンル編集</h1>
  </div>
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <!--ジャンル追加-->
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <div class="row g-3 align-items-center mb-5">
    <div class="col-auto">
      <label for="inputPassword6" class="col-form-label">ジャンル名</label>
    </div>
    <div class="col-auto">
        <%= form_with model:@genre,url:admin_genre_path,local:true do |f|%>
          <div class="row g-3 align-items-center">
            <div class="col-auto">
              <%= f.text_field :name,autofocus:true,class:"form-control"%>
            </div>
            <div class="action col-auto">
              <%= f.submit "変更を保存",class:"btn btn-success"%>
            </div>
          </div>
        <%end%>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  
  <div class="row mb-2">
    <h4 class="offset-1 bg-light">ジャンル一覧・追加</h1>
  </div>
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <!--ジャンル追加-->
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <div class="row g-3 align-items-center mb-5">
    <div class="col-auto">
      <label for="inputPassword6" class="col-form-label">ジャンル名</label>
    </div>
    <div class="col-auto">
        <%= form_with model:@genre,url:admin_genres_path,local:true do |f|%>
          <div class="row g-3 align-items-center">
            <div class="col-auto">
              <%= f.text_field :name,autofocus:true,class:"form-control"%>
            </div>
            <div class="action col-auto">
              <%= f.submit "新規登録",class:"btn btn-success"%>
            </div>
          </div>
        <%end%>
    </div>
  </div>
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <!--ジャンル追加-->
  <!--/////////////////////////////////////////////////////////////////////////////-->
  
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <!--ジャンル一覧-->
  <!--/////////////////////////////////////////////////////////////////////////////-->
    <table class="table w-25">
      <thead class="bg-light">
        <tr>
          <th scope="col" colspan="2">ジャンル</th>
        </tr>
      </thead>

      <tbody>
          <%@genres.each do |genre| %>
            <tr class="">
              <th scope="row"><%= genre.name%></th>
              <td><%= link_to "編集する",edit_admin_genre_path(genre.id),class:"btn btn-success"%></td>
            </tr>
          <%end%>
      </tbody>   
    </table>
  <!--/////////////////////////////////////////////////////////////////////////////-->
  <!--ジャンル一覧-->
  <!--/////////////////////////////////////////////////////////////////////////////-->
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mb-2">
    <h4 class="offset-1 bg-light">商品登録</h1>
  </div>
  
  <div class="container w-50">
    <%=form_with model: @item,url:admin_item_path(@item.id),local:true do |f| %>
      <div class="row mb-3">
        <label for="inputEmail3" class="col-4 col-form-label">商品画像</label>
        <div class="col-8">
          <%= f.attachment_field :image %>
          <p></p>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">商品名</label>
        <div class="col-8">
          <%= f.text_field :name,autofocus:true,class:"form-control"%>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">商品説明</label>
        <div class="col-8">
          <%= f.text_area :introduction,autofocus:true,class:"form-control"%>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">ジャンル</label>
        <div class="col-8">
          <%= f.select :genre_id, @genres.map{ |genre| [genre.name,genre.id] },{include_blank: "選択して下さい"},{class:"form-control"}%>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">税抜価格</label>
        <div class="col-8">
          <%= f.text_field :price,autofocus:true,class:"form-control",placeholder:1000 %>
        </div>
      </div>
       
      <div class="row mb-3 align-items-center">
        <label class="col-form-label col-4">販売ステータス</label>
        <div class="col-8">
          <div class="form-check-inline">
            <div class="form-check">
              <label class="form-check-label"><%= f.radio_button :is_active,true %>販売中</label>
            </div>
            <div class="form-check">
               <label class="form-check-label"><%= f.radio_button :is_active,false %>販売停止中</label>
            </div>
          </div>
        </div>
      </div>
      
      <div class="action d-flex justify-content-center">
        <%= f.submit "新規登録",class:"btn btn-success"%>
      </div>
    <%end%>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h3 class="row justify-content-end">
    <%= link_to "+",new_admin_item_path ,class:"bg-info text-light rounded-circle px-2 text-decoration-none"%>
  </h3>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">商品ID</th>
          <th scope="col">商品名</th>
          <th scope="col">税抜き価格</th>
          <th scope="col">ジャンル</th>
          <th scope="col">販売ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <th scope="row"><%= item.id %></th>
            <td>
              <%= link_to(admin_item_path(item.id)) do%>
                <%= item.name %>
              <% end%>
              </td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <td><%= item.is_active ? "販売中" : "停止中"%></td>
          </tr>
        <% end %>  
      </tbody>
    </table>
    </div>
  </div>  

app/views/admin/items/new.html.erb
<div class="container">
  
  <% if @item.errors.any? %>
    <%= @item.errors.count %>件のエラーが発生しました
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
  <div class="row mb-2">
    <h4 class="offset-1 bg-light">商品登録</h1>
  </div>
  
  <div class="container w-50">
    <%=form_with model: @item,url:admin_items_path,local:true do |f| %>
      <div class="row mb-3">
        <label for="inputEmail3" class="col-4 col-form-label">商品画像</label>
        <div class="col-8">
          <%= f.attachment_field :image %>
          <p></p>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">商品名</label>
        <div class="col-8">
          <%= f.text_field :name,autofocus:true,class:"form-control"%>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">商品説明</label>
        <div class="col-8">
          <%= f.text_area :introduction,autofocus:true,class:"form-control"%>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">ジャンル</label>
        <div class="col-8">
          <%= f.select :genre_id, @genres.map{ |genre| [genre.name,genre.id] },{include_blank: "選択して下さい"},{class:"form-control"}%>
        </div>
      </div>
      
      <div class="row mb-3">
        <label for="inputPassword3" class="col-4 col-form-label">税抜価格</label>
        <div class="col-8">
          <%= f.text_field :price,autofocus:true,class:"form-control",placeholder:1000 %>
        </div>
      </div>
       
      <div class="row mb-3 align-items-center">
        <label class="col-form-label col-4">販売ステータス</label>
        <div class="col-8">
          <div class="form-check-inline">
            <div class="form-check">
              <label class="form-check-label"><%= f.radio_button :is_active,true %>販売中</label>
            </div>
            <div class="form-check">
               <label class="form-check-label"><%= f.radio_button :is_active,false %>販売停止中</label>
            </div>
          </div>
        </div>
      </div>
      
      <div class="action d-flex justify-content-center">
        <%= f.submit "新規登録",class:"btn btn-success"%>
      </div>
    <%end%>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mb-4">
    <h4 class="offset-1 bg-light">商品詳細</h1>
  </div>
  
  <div class="container d-flex">
    
    <div class="row col-6">
      <%= attachment_image_tag @item, :image, format: 'jpeg', size: '300x300' %>
    </div>
    
     <div class="row col-6">
      <!--<div class="row mb-3 align-items-center">-->
      <!--  <label for="inputEmail3" class="col-form-label">商品名</label>-->
      <!--  <div class="col-8">-->
      <!--     <%= @item.name %>-->
      <!--  </div>-->
      <!--</div>-->
      
      <!--<div class="row mb-3 align-items-center">-->
      <!--  <label for="inputPassword3" class="col-form-label">商品説明</label>-->
      <!--  <div class="col-8">-->
      <!--      <%= @item.introduction %>-->
      <!--  </div>-->
      <!--</div>-->
      
      <!--<div class="row mb-3 align-items-center">-->
      <!--  <label for="inputPassword3" class="col-form-label">ジャンル</label>-->
      <!--  <div class="col-8">-->
      <!--      <%= @item.genre.name %>-->
      <!--  </div>-->
      <!--</div>-->
      
      <!--<div class="row mb-3 align-items-center">-->
      <!--  <label for="inputPassword3" class="col-form-label">税込価格</br> (税抜価格)</label>-->
      <!--  <div class="col-8">-->
      <!--      <%= @item.price %></br>-->
      <!--      <%= "(#{(@item.price*1.1).floor})" %>-->
      <!--  </div>-->
      <!--</div>-->
      
      <!--<div class="row mb-3 align-items-center">-->
      <!--  <label for="inputPassword3" class="col-form-label">販売ステータス</label>-->
      <!--  <div class="col-8">-->
      <!--     <%= @item.is_active ? "販売中" : "停止中" %>-->
      <!--  </div>-->
      <!--</div>-->
       
      
      <!--<div class="action d-flex justify-content-center">-->
     
      <!--</div>-->
      
      <table class="table">
          <tbody>
              <tr>
                  <td>商品名</td>
                  <td><%= @item.name %></td>
              </tr>
              <tr>
                  <td>商品説明</td>
                  <td><%= @item.introduction %></td>
              </tr>
              <tr>
                  <td>ジャンル</td>
                  <td><%= @item.genre.name %></td>
              </tr>
              <tr>
                  <td>税込価格</br> (税抜価格)</td>
                  <td><%= @item.price %></br>
                    <%= "(#{(@item.price*1.1).floor})" %>
                　</td>
            　</tr>
              <tr>
                  <td>販売ステータス</td>
                  <td><%= @item.is_active ? "販売中" : "停止中" %></td>
              </tr>
          </tbody>
      </table>
      
      <div>
        <%= link_to("編集する",edit_admin_item_path(@item.id),{class:"btn btn-success"}) %>
      </div>
      
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container w-75">
  <div class="row mb-2 justify-content-between">
    <h4 class="bg-light">注文履歴一覧</h1>
  </div>
  <div class="row justify-content-center">
    <table class="table table-bordered w-75">
      <thead>
        <tr>
          <th class="table-active">購入日時</th>
          <th class="table-active">購入者</th>
          <th class="table-active">注文個数</th>
          <th class="table-active">支払いステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="align-middle"><%=  link_to (l order.created_at, format: :short),admin_order_path(order.id) %></td>
            <td class="align-middle"><%= order.customer.last_name + '' + order.customer.first_name %></td>
            <td class="align-middle"><%= order.order_details.inject(0){ | amount,detail | amount + detail.count} %></td>
            <td class="align-middle"><%= order.order_status_i18n %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  
  <div class="d-flex justify-content-center">
    <%= paginate @orders %>
  </div>
  
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mb-2 justify-content-between">
    <h4 class="bg-light">注文履歴詳細</h1>
  </div>
  
  <div class="row mb-3">
    <table class="table w-50">
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to (@order.customer.last_name + '' + @order.customer.first_name) ,admin_customer_path(@order.customer.id) %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= l @order.created_at, format: :short %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <%= @order.shipping_postal %>
            <%= @order.shipping_address %></br>
            <%= @order.shipping_name %>
          </td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model:@order,url:admin_order_path(@order.id),local:true do |f| %>
              <%= f.select :order_status,Order.order_statuses.keys.map{ |k| [I18n.t("enums.order.order_status.#{k}"),k]} %>
              <%= f.submit "更新",class:"btn btn-success btn-sm" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <div class="row">
    <div class="col-8">
      <table class="table table-bordered">
         <thead class="table-active">
           <tr>
             <th>商品名</th>
             <th>単価（税込）</th>
             <th>数量</th>
             <th>小計</th>
             <th>制作ステータス</th>
           </tr>
         </thead>
         <tbody>
           <% @order.order_details.each do |order_detail| %>
             <tr>
               <td><%= order_detail.item.name %></td>
               <td><%= order_detail.tax_inclouded_price.to_s(:delimited) %></td>
               <td><%= order_detail.count %></td>
               <td><%= (order_detail.tax_inclouded_price * order_detail.count).to_s(:delimited) %> </td>
               <td>
                 <%= form_with model:order_detail,url:admin_order_detail_path(order_detail.id),local:true do |f| %>
                   <%= f.select :making_status,OrderDetail.making_statuses.keys.map{ |k| [I18n.t("enums.order_detail.making_status.#{k}"),k]} %>
                   <%= f.submit "更新",class:"btn btn-success btn-sm" %>
                 <% end %>
               </td>
             </tr>    
             
           <% end %>
           
         </tbody>
      </table>
    </div>
    
    <div class="col-3">
      <table class="table">
        <tr>
          <th>商品合計</th>
          <td><%= "#{(@order.total_payment - @order.postage).to_s(:delimited)}円" %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= "#{@order.postage}円" %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= "#{@order.total_payment.to_s(:delimited)}円" %></td>
        </tr>
      </table>
    </div>
    
  </div>
</div>