config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/admin" => "homes#top"
  get "homes/about"=> "homes#about",as:"about"
  
  get "admin/searches/search" => "admin/searches#search",as:"admin_search"
  get "admin/searches/genre_search" => "admin/searches#genre_search",as:"admin_genre_search"
  
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,except: [:destroy]
    resources :customers,only: [:index,:edit,:update,:show]
    resources :orders,only:[:show,:update,:index]
    resources :order_details,only:[:update]
  end
  
  devise_for :admin,skip: [:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }
  
  get "customers/my_page" => "public/customers#show",as:"my_page"
  get "customers/unsubscribe" => "public/customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdraw" => "public/customers#withdraw",as:"withdraw"
  delete "cart_items/destroy_all" => "public/cart_items#destroy_all",as:"destroy_all"
  get "orders/complete" => "public/orders#complete",as:"complete"
  post "orders/confirm" => "public/orders#confirm",as:"confirm"
  get "searches/search" => "public/searches#search",as:"search"
  get "searches/genre_search" => "public/searches#genre_search",as:"genre_search"
  
  scope module: :public do
    resource :customers,except: [:new,:create]
    resources :addresses,except: [:show,:new]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:create,:update,:destroy]
    resources :orders,only:[:index,:new,:create,:show]
  end
  
  devise_for :customers,skip: [:passwords,],controllers:{
     registrations: "public/registrations",
     sessions: "public/sessions"
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  belongs_to :customer
  
  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true
  belongs_to :customer
  belongs_to :item
  validates :amount,presence: true
  
  def subtotal
    item.with_tax_price*amount
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name,presence: true
  has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  attachment :image
  validates :image,presence: true
  
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card:0,transfer:1}
  enum order_status: {waiting:0,confirmation:1,making:2,preparation:3,sent:4}
  belongs_to :customer
  has_many :order_details,dependent: :destroy
  
  def address_display
    "〒" + shipping_postal + " " + shipping_address + " " + shipping_name
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: {not_startable:0,waiting:1,making:2,complete:3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    genres = Genre.all
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path(genres)
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    genres = Genre.all
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genres)
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @genres = Genre.all
    @item = Item.new
  end
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    @orders = Order.page(params[:page]).order(id: "desc").per(8)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.order_status == "confirmation"
      order.order_details.update_all(making_status: "waiting")
    end
    order.save
    redirect_to admin_order_path(order.id)
  end
  
  private
  
  def order_params
    params.require(:order).permit(:order_status)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def test
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @genres = Genre.all
  end
  
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container">
  
  <div class="row d-flex justify-content-center mb-5">
    <h1>ABOUT</h1>
  </div>
  
  <div class="row d-flex justify-content-center text-center lead">
    <p>ながのCAKEは全国発送可能なケーキ屋さんです。</br>
    お子様からお年寄りの方までお召し上がりいただけるよう</br>
    様々なバリエーションをご用意しております。</br>
    また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</br>
    ぜひ、ご注文ください。
    </p>
  </div>
  
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render "public/searches/genre_search",genres: @genres%>
    </div>

    <div class="col-9">
      <div class="row mb-5">
        <div class="card w-75">
          <%= image_tag "top_image.jpeg",class:"bd-placeholder-img bd-placeholder-img-lg card-img" %>
          <div class="card-img-overlay d-flex justify-content-center align-items-center">
            <p class="card-text text-black-50 ">
              ようこそ、ながのCAKEへ！</br>
              このサイトは、ケーキ販売のECサイトになります。</br>
              じゃない方も閲覧はできますが、</br>
              購入には会員登録が必要になります。
            </p>
          </div>
        </div>
      </div>
      
      <div class="row flex-column">
        <h2>新着商品</h2>
        <div class="d-flex flex-wrap">
          <% @items.each do |item| %>
            <div class="item pr-1 mb-3">
              <div>
                <%= link_to item_path(item.id) do %>
                  <%= attachment_image_tag item, :image, format: 'jpeg', size: '200x200' ,class:"mb-2" %>
                <% end %>
              </div>
              <p class="font-weight-bold">
                <%= item.name %></br>
                <%= number_to_currency(item.price,unit: "¥",strip_insignificant_zeros: true) %>
              </p>
            </div>
          <% end %>
        </div>
        <%= link_to "全ての商品を見る >",items_path ,class:"ml-auto"%>
      </div>
      </div>
    </div>
  </div>
</div>