config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/admin" => "homes#top"
  get "homes/about"=> "homes#about",as:"about"
  
  get "admin/searches/search" => "admin/searches#search",as:"admin_search"
  get "admin/searches/genre_search" => "admin/searches#genre_search",as:"admin_genre_search"
  
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,except: [:destroy]
    resources :customers,only: [:index,:edit,:update,:show]
    resources :orders,only:[:show,:update,:index]
    resources :order_details,only:[:update]
  end
  
  devise_for :admin,skip: [:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }
  
  get "customers/my_page" => "public/customers#show",as:"my_page"
  get "customers/unsubscribe" => "public/customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdraw" => "public/customers#withdraw",as:"withdraw"
  delete "cart_items/destroy_all" => "public/cart_items#destroy_all",as:"destroy_all"
  get "orders/complete" => "public/orders#complete",as:"complete"
  post "orders/confirm" => "public/orders#confirm",as:"confirm"
  get "searches/search" => "public/searches#search",as:"search"
  get "searches/genre_search" => "public/searches#genre_search",as:"genre_search"
  
  scope module: :public do
    resource :customers,except: [:new,:create]
    resources :addresses,except: [:show,:new]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:create,:update,:destroy]
    resources :orders,only:[:index,:new,:create,:show]
  end
  
  devise_for :customers,skip: [:passwords,],controllers:{
     registrations: "public/registrations",
     sessions: "public/sessions"
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  belongs_to :customer
  
  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true
  belongs_to :customer
  belongs_to :item
  validates :amount,presence: true
  
  def subtotal
    item.with_tax_price*amount
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name,presence: true
  has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  attachment :image
  validates :image,presence: true
  
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card:0,transfer:1}
  enum order_status: {waiting:0,confirmation:1,making:2,preparation:3,sent:4}
  belongs_to :customer
  has_many :order_details,dependent: :destroy
  
  def address_display
    "〒" + shipping_postal + " " + shipping_address + " " + shipping_name
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: {not_startable:0,waiting:1,making:2,complete:3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @genres = Genre.all
    @item = Item.new
  end
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def test
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @genres = Genre.all
  end
  
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" style="min-height:100vh;">
    
    <div class="mb-5">
    <header class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
      <h1 class="navbar-brand mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <%= link_to root_path,class:"text-dark" do %>
          <%= image_tag 'ショートケーキアイコン.jpeg',size:"30x30",class:"d-inline-block align-middle" %>
          <p class="navbar-brand">nagano cake</p>
        <%end%>
      </h1>
      <div class="">
        <% if admin_signed_in?%>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "商品一覧",admin_items_path,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "会員一覧",admin_customers_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "注文履歴一覧",admin_orders_path,class:"nav-link"  %></li>
            <li class="nav-item"><%= link_to "ジャンル一覧",admin_genres_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class:"nav-link"  %></li>
          </ul>
          <div class="input-group">
            <%= form_with url:admin_search_path ,class:"form-inline", method: :get,local:true do |f| %>
              <%= f.text_field :content ,class:"form-control"%>
              <%= f.submit "検索",class:"btn btn-primary ml-1"%>
            <%end%>
          </div>
        <%elsif customer_signed_in? %>
          <%= "#{current_customer.last_name}さん、こんにちは！" %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "マイページ",my_page_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "商品一覧",items_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "カート",cart_items_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "ログアウト",destroy_customer_session_path ,method: :delete,class:"nav-link" %></li>
          </ul>
          <div class="input-group">
            <%= form_with url:search_path ,class:"form-inline", method: :get,local:true do |f| %>
              <%= f.text_field :content ,class:"form-control"%>
              <%= f.submit "検索",class:"btn btn-primary ml-1"%>
            <%end%>
          </div>
        <%else%>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "About",about_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "商品一覧",items_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "新規登録",new_customer_registration_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "ログイン",new_customer_session_path ,class:"nav-link" %></li>
            <li class="nav-item"><%= link_to  "管理者用",new_admin_session_path,class:"nav-link" %></li>
          </ul>
          <div class="input-group">
            <%= form_with url:search_path ,class:"form-inline", method: :get,local:true do |f| %>
              <%= f.text_field :content ,class:"form-control"%>
              <%= f.submit "検索",class:"btn btn-primary ml-1"%>
            <%end%>
          </div>
        <% end%>
        
      </div>
      
    </header>
  </div>
  <div class="flex-fill">
      <%= yield %>
  </div>

    <footer class="d-flex justify-content-center border-top">
      <div>
        <%= link_to root_path,class:"text-dark" do %>
          <%= image_tag 'ショートケーキアイコン.jpeg',size:"30x30",class:"d-inline-block align-middle" %>
          <h2 class="navbar-brand">nagano cake</h2>
        <%end%>
      </div>
    </footer>
  </body>
</html>